deploy_prod:
    stage: deploy
    environment:
        name: prod
        url: 157.26.77.153
    tags:
        - appweb
    script:
        - cd /var/www/php/AWb-g3-ForMax/main
        - git checkout main
        - git pull origin main
    only:
        - main